CompileFlags:
  Add:
    - "-ferror-limit=0"
Hover:
  ShowAKA: No
InlayHints:
  TypeNameLimit: 24

Diagnostics:
  Suppress:
    - "variadic_device_fn"
    - "attributes_not_allowed"
---
If:
  PathMatch: .*\.cuh
CompileFlags:
  Add:
    - --cuda-path=/usr/local/cuda
    - --cuda-gpu-arch=sm_90
    - -I/usr/local/cuda/include
    - "-xcuda"
    - --std=c++17
    - "-D__INTELLISENSE__"
    - "-D__CLANGD__"
    - "-DCUDA_12_0_SM90_FEATURES_SUPPORTED"
    - "-DCUTLASS_ARCH_MMA_SM90_SUPPORTED=1"
    - "-D_LIBCUDACXX_STD_VER=12"
    - "-D__CUDACC_VER_MAJOR__=12"
    - "-D__CUDACC_VER_MINOR__=9"
    - "-D__CUDA_ARCH__=900"
    - "-D__CUDA_ARCH_FEAT_SM90_ALL"
    - "-Wno-invalid-constexpr"
  Remove:
    - "-Xcudafe"
    - "--diag_suppress*"
    - "-Xcompiler=-fPIC"
    - "-Xfatbin*"
    - "-gencode*"
    - "--generate-code*"
    - "-ccbin*"
    - "--compiler-options*"
    - "--expt-extended-lambda"
    - "--expt-relaxed-constexpr"
    - "-forward-unknown-to-host-compiler"
    - "-Werror=cross-execution-space-call"
---
If:
  PathMatch: .*\.cu
CompileFlags:
  Add:
    - --cuda-path=/usr/local/cuda
    - --cuda-gpu-arch=sm_90
    - -I/usr/local/cuda/include
    - "-xcuda"
    - --std=c++17
    - "-D__INTELLISENSE__"
    - "-D__CLANGD__"
    - "-DCUDA_12_0_SM90_FEATURES_SUPPORTED"
    - "-DCUTLASS_ARCH_MMA_SM90_SUPPORTED=1"
    - "-D_LIBCUDACXX_STD_VER=12"
    - "-D__CUDACC_VER_MAJOR__=12"
    - "-D__CUDACC_VER_MINOR__=9"
    - "-D__CUDA_ARCH__=900"
    - "-D__CUDA_ARCH_FEAT_SM90_ALL"
    - "-Wno-invalid-constexpr"
  Remove:
    - "-Xcudafe"
    - "--diag_suppress*"
    - "-Xcompiler=-fPIC"
    - "-Xfatbin*"
    - "-gencode*"
    - "--generate-code*"
    - "-ccbin*"
    - "--compiler-options*"
    - "--expt-extended-lambda"
    - "--expt-relaxed-constexpr"
    - "-forward-unknown-to-host-compiler"
    - "-Werror=cross-execution-space-call"